OpenWines\ReferencesBundle\Entity\Appellation:
    repositoryClass: OpenWines\ReferencesBundle\Repository\AppellationRepository
    type: entity
    table: openwines_ref_appellation
    changeTrackingPoloicy: DEFERRED_EXPLICIT
    lifecycleCallbacks:
        prePersist: [ prePersist ]
        postPersist: [ postPersist ]
    manyToOne:
        region:
            targetEntity: OpenWines\ReferencesBundle\Entity\Region
            inversedBy: appellations
            joinColumn:
                name: region_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            nullable: false
            unique: true
            length: 255
        name:
            type: string
            length: 255
            unique: false
            nullable: false
        appellation_type:
            type: string
            length: 255
            unique: false
            nullable: true
        area:
            type: integer
            length: 255
            unique: false
            nullable: true
        annual_production_quantity:
            type: integer
            unique: false
            nullable: true
        soil:
            type: string
            length: 255
            unique: false
            nullable: true
        wine_sweetness:
            type: string
            length: 255
            unique: false
            nullable: true
        wine_sparklingness:
            type: string
            length: 255
            unique: false
            nullable: true
        wine_color:
            type: string
            length: 255
            unique: false
            nullable: true
        description:
            type: text
            unique: false
            nullable: true
        odg_name:
            type: string
            length: 255
            unique: false
            nullable: true
        odg_url:
            type: string
            length: 255
            unique: false
            nullable: true
        wikipedia_url:
            type: string
            length: 255
            unique: false
            nullable: true
        wikidata_url:
            type: string
            length: 255
            unique: false
            nullable: true
        image_url:
            type: string
            length: 255
            unique: true
            nullable: true
        creation_year:
            type: integer
            unique: false
            nullable: true
        created:
            type: datetime
            unique: false
            nullable: true
        updated:
            type: datetime
            unique: false
            nullable: true