OpenWines\ReferencesBundle\Entity\Appellation:
    repositoryClass: OpenWines\ReferencesBundle\Repository\AppellationRepository
    type: entity
    table: openwines_ref_appellation
    changeTrackingPoloicy: DEFERRED_EXPLICIT
    lifecycleCallbacks:
        prePersist: [ prePersist ]
        postPersist: [ postPersist ]
    manyToOne:
        region:
            targetEntity: OpenWines\ReferencesBundle\Entity\Region
            inversedBy: appellations
            joinColumn:
                name: region_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            nullable: false
            unique: true
            length: 255
        name:
            type: string
            length: 255
            unique: false
            nullable: false
        type:
            type: string
            length: 255
            unique: false
            nullable: true
        year:
            type: smallint
            unique: false
            nullable: true
        departments:
            type: simple_array
            unique: false
            nullable: true
        sun_exposure_yearly_hours:
            type: smallint
            unique: false
            nullable: true
        climate:
            type: string
            length: 255
            unique: false
            nullable: true
        area:
            type: smallint
            unique: false
            nullable: true
        winegrowers_count:
            type: smallint
            unique: false
            nullable: true
        annual_production_quantity:
            type: smallint
            unique: false
            nullable: true
        soil:
            type: simple_array
            unique: false
            nullable: true
        density:
            type: smallint
            unique: false
            nullable: true
        yield_per_hectare_min:
            type: smallint
            unique: false
            nullable: true
        yield_per_hectare_max:
            type: smallint
            unique: false
            nullable: true
        wine_types:
            type: simple_array
            unique: false
            nullable: true
        wine_sweetness:
            type: simple_array
            unique: false
            nullable: true
        wine_color:
            type: simple_array
            unique: false
            nullable: true
        wine_sparklingness:
            type: simple_array
            unique: false
            nullable: true
        varietals:
            type: simple_array
            unique: false
            nullable: true
        description:
            type: text
            unique: false
            nullable: true
        odg_name:
            type: string
            length: 255
            unique: false
            nullable: true
        odg_url:
            type: string
            length: 255
            unique: false
            nullable: true
        wikipedia_url:
            type: string
            length: 255
            unique: false
            nullable: true
        wikidata_url:
            type: string
            length: 255
            unique: false
            nullable: true
        image_url:
            type: string
            length: 255
            unique: true
            nullable: true
        created:
            type: datetime
            unique: false
            nullable: true
        updated:
            type: datetime
            unique: false
            nullable: true