datagrid:
    appellation:
        options:
            entityHint: appellation
        source:
            type: pim_datasource_default
            entity: OpenWines\ReferencesBundle\Entity\Appellation
            repository_method: createDatagridQueryBuilder
        columns:
            code:
                label: Code
            name:
                label: Name
            type:
                label: Type
            wine_sweetness:
                label: Sweetness
            wine_sparklingness:
                label: Sparklingness
            wine_color:
                label: Color
            annual_production_quantity:
                label: Production (hl)
            soil:
                label: Soil
            area:
                label: Area (ha)
            year:
                label: Creation
        properties:
            id: ~
            show_link:
                type: url
                route: pim_customentity_show
                params:
                    - id
                    - customEntityName
            edit_link:
                type: url
                route: pim_customentity_edit
                params:
                    - id
                    - customEntityName
            delete_link:
                type: url
                route: pim_customentity_delete
                params:
                    - id
                    - customEntityName
        actions:
            show:
                type:      navigate
                label:     Show the reference data
                icon:      eye-open
                link:      show_link
            edit:
                type:      navigate
                label:     Edit the reference data
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: Delete the reference data
                icon:  trash
                link:  delete_link
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: rd.code
                name:
                    type:      string
                    label:     Name
                    data_name: rd.name
                type:
                    type:      choice
                    label:     Type
                    data_name: rd.type
                wine_color:
                    type:      choice
                    label:     Color
                    data_name: rd.wine_color
                    options:
                        field_options:
                            multiple: true
                            choices: @openwines.form.appellation->getColors
                wine_sweetness:
                    type:      choice
                    label:     Sweetness
                    data_name: rd.wine_sweetness
                    options:
                        field_options:
                            multiple: true
                            choices: @openwines.form.appellation->getSweetnesses
                wine_sparklingness:
                    type:      choice
                    label:     Sparklingness
                    data_name: rd.wine_sparklingness
                    options:
                        field_options:
                            multiple: true
                            choices: @openwines.form.appellation->getSparklingnesses
                soil:
                    type:      choice
                    label:     Soil
                    data_name: rd.soil
                    options:
                        field_options:
                            multiple: true
                            choices: @openwines.form.appellation->getSoils

                annual_production_quantity:
                    type:      number
                    label:     Production
                    data_name: rd.annual_production_quantity
                area:
                    type:      number
                    label:     Area
                    data_name: rd.area
                year:
                    type:      number
                    label:     Creation
                    data_name: rd.year

        sorters:
            columns:
                code:
                    data_name: rd.code
                name:
                    data_name: rd.name
                type:
                    data_name: rd.type
                wine_color:
                    data_name: rd.wine_color
                wine_sweetness:
                    data_name: rd.wine_sweetness
                wine_sparklingness:
                    data_name: rd.wine_sparklingness
                annual_production_quantity:
                    data_name: rd.annual_production_quantity
                area:
                    data_name: rd.area
                year:
                    data_name: rd.year

            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'