parameters:
  regions:
    types:
      big: grand terroir
      small: terroir de petite taille
      disappeared: terroir disparu
    countries:
      France: France
      Germany: Germany
      Italy: Italy
      Spain: Spain
      US: United States
  appellations:
    types:
      Other: Autre
      IGP: Indication Géographique Protégée
      AOP: Appellation d'Origine Protégée
      AOC: Appellation d'Origine Controlée
      PDO: Protected Designation of Origin
      PGI: Protected Geographical Indication
      TSG: Traditional Specialities Guaranteed
      GI: Geographical Indication
      DVA: Designated Viticultural Area
      AVA: American Viticultural Area
      DO: Denominación de Origen
      DOC: Denominazione di Origine Controllata
      DOCG: Denominazione di Origine Controllata e Garantita
      DOP: Denominazione di Origine Protetta
      QbA: Qualitätswein bestimmter Anbaugebiete
      QmP: Qualitätswein mit Prädikat
  wines:
    colors:
      red: red
      white: white
      rosé: rosé
    sweetness:                  # sucre, douceur, sécheresse
      brut-nature: brut-nature
      extra-brut: extra-brut
      brut: brut
      extra-dry: extra-dry      # très sec, entre 0 et 2 g/l
      dry: dry                  # sec
      medium-dry: medium-dry    # demi-sec, entre 10 et 20 g/l
      sweet: sweet              # moëlleux, doux, entre 20 et 40 g/l
      dessert: dessert          # liquoreux, plus de 40 g/l
    sparklingness:                    # effervescence
      still: still                    # tranquille
      semi-sparkling: semi-sparkling  # pétillant
      sparkling: sparkling            # effervescent/fines bulles
