<?php

namespace OpenWines\ReferencesBundle\Repository;

use Doctrine\ORM\NoResultException;

/**
 * VarietalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VarietalRepository extends BaseRepository
{
    /**
     * used in DQL expressions
     */
    const QUERY_ALIAS = 'c';

    /** ************* */
    /** F I N D E R S */


    /** *************** */
    /** B U I L D E R S */
}
